### ISSUE TITLE
Error loading the plugin 

### ISSUE THREAD

**Issue by Falow1** [punteroo/TF2-Item-Plugins#11]
This error happens:

L 10/30/2021 - 18:20:04: [SM] Exception reported: Invalid convar handle 0 (error 4)
L 10/30/2021 - 18:20:04: [SM] Blaming: tf2item_weapons.smx
L 10/30/2021 - 18:20:04: [SM] Call stack trace:
L 10/30/2021 - 18:20:04: [SM]   [0] ConVar.BoolValue.get
L 10/30/2021 - 18:20:04: [SM]   [1] Line 109, tf2item_weapons.sp::OnMapStart

**Comment by punteroo** [comment]
I need more information regarding this error as I can't seem to replicate it with latest builds.

Can you inform me the version you are utilizing for `tf2item_weapons`? It must be latest v3.0.2.
Run ``sm plugins info tf2item_weapons.smx`` on your server console and send output.

**Comment by punteroo** [comment]
After some testing I have found the issue. This happens when late loading the plugin (ex: reloading it).

I have issued a fix on a recent commit, while also adding new features for v3.1.0.

New release should be up shortly.

**Comment by punteroo** [comment]
This has been fixed in latest v3.1.0 release: https://github.com/punteroo/TF2-Item-Plugins/releases/tag/v3.1.0
Thank you for reporting this issue!
