### ISSUE TITLE
Bug with the golden frying pan

### ISSUE THREAD

**Issue by Falow1** [punteroo/TF2-Item-Plugins#19]
When the gold frying pan is selected and you put killstreak on it, the weapon simply turns into a club when you rejoin the same server,I checked the log and it's something with the TF2Items.

**Comment by gdfsgdfg** [comment]
Not just that one I think all overrides do that, I thought the thing didn't have cookies, weird that it "remembers" that one.

**Comment by punteroo** [comment]
Without more information about what TF2Items is telling you I cannot know for sure if this is an issue on my part or TF2Items'. Please be sure to post a log containing the error message you're getting so I can assist further and mark this as a bug.

**Comment by gdfsgdfg** [comment]
I have managed to replicate this bug easily. Set an override for the golden pan then type retry in console. You will return with your melee weapon replaced by a default bat. This might happen with other weapons as well since someone said they got a default smg.

**Comment by gdfsgdfg** [comment]
Temporary fix right now is to make it so it doesn't have cookies saved on players.

So just clear "pPreferences = CV_UseCookies.BoolValue ? RegClientCookie("tf2item_weapons_prefs", "Weapon override preferences set for this user.", CookieAccess_Private) : INVALID_HANDLE;" and compile. No more issues.

**Comment by punteroo** [comment]
Hello.

Giving yourself weapons you don't own is no longer supported on the new version.
I will however implement a way of equipping both cosmetics and weapons to override current inventories in the future.
