### ISSUE TITLE
It doesn't output anything when manually updating the unusual names.

### ISSUE THREAD

**Issue by JaredKnushfurReal** [punteroo/TF2-Item-Plugins#21]
I put in the correct pathing (at least I assume so because it never gives me an error) but no output file is created when updating the unusual names

Here's my command. (py "D:\steamgames\steamapps\common\team fortress 2\tf\addons\sourcemod\translations\unusual_names_updater.py" -tf "D:\steamgames\steamapps\common\team fortress 2\tf\resource\tf_english.txt" -out "D:\unusuals.phrases.txt")

**Comment by punteroo** [comment]
With only the command I cannot assist you.
Please post a log of what the script is outputting when ran.
