### ISSUE TITLE
"Unknown command: sm_hats"

### ISSUE THREAD

**Issue by ghost** [punteroo/TF2-Item-Plugins#24]
Only the VIP commands work for me. Typing any of the rest of the commands outputs an unknown command issue.

**Comment by punteroo** [comment]
Si estás teniendo ese output significa que los plugins en sí no cargaron. Podes ver si los plugins que querés usar cargaron bien en tu servidor usando `sm plugins list` en la rcon, si tienen algún error te lo va a decir y tenés que buscar cuál es en los logs de tu servidor cuando estaba arrancando.
El mayor de los casos los plugins no cargan por:
- Gamedata desactualizado
- Mala versión de las extensiones
- Falta de dependencias

Asegurate de tener los requerimientos dentro del [readme](https://github.com/punteroo/TF2-Item-Plugins/blob/production/README.md) y validar tus logs de error para entender por donde viene la mano.
