### ISSUE TITLE
Commands not working for other players

### ISSUE THREAD

**Issue by ghost** [punteroo/TF2-Item-Plugins#25]
The plugin works now, but only me can access the command, the rest of the server aren't allowed to use the command, what do i do?

**Comment by punteroo** [comment]
Please refer to using SourceMod's integrated command access overrides feature. I'll link it for you here: https://wiki.alliedmods.net/Overriding_Command_Access_(Sourcemod)

By default, all commands require the `ADMFLAG_RESERVATION` flag active.
I'll be closing this.
