### ISSUE TITLE
No funciona nada

### ISSUE THREAD

**Issue by Dylan2004nn** [punteroo/TF2-Item-Plugins#27]
Instale la ultima version del plugin todo bien, ya tengo de hace rato los plugins requeridos pero no funciona este en particular.

Al abrir el menu !vip y elegir uno de las dos primeras opciones me sale este error en consola.

L 06/17/2024 - 14:52:07: [SM] Exception reported: Invalid Handle 0 (error 4)
L 06/17/2024 - 14:52:07: [SM] Blaming: tf_econ_data.smx
L 06/17/2024 - 14:52:07: [SM] Call stack trace:
L 06/17/2024 - 14:52:07: [SM]   [0] SDKCall
L 06/17/2024 - 14:52:07: [SM]   [1] Line 371, tf_econ_data.sp::GetEconItemDefinition
L 06/17/2024 - 14:52:07: [SM]   [2] Line 296, tf_econ_data/item_definition.sp::LoadEconItemDefinitionString
L 06/17/2024 - 14:52:07: [SM]   [3] Line 33, tf_econ_data/item_definition.sp::Native_GetItemName
L 06/17/2024 - 14:52:07: [SM]   [5] TF2Econ_GetItemName
L 06/17/2024 - 14:52:07: [SM]   [6] Line 1263, E:\Keep\Programming\Git Repos\TF2-Item-Plugins\scripting\tf2item_weapons.sp::mMainMenu
L 06/17/2024 - 14:52:07: [SM]   [7] Line 125, E:\Keep\Programming\Git Repos\TF2-Item-Plugins\scripting\tf2item_weapons.sp::CMD_Weapons

no se que hacer

**Comment by punteroo** [comment]
Buenas.

El pack de plugins es muy viejo y no tenia pensado en todos estos años reescribirlo.
He comenzado la semana anterior con una reescritura del pack de plugins entero, tanto armas como cosmeticos en la branch [`feat/rewrite`](https://github.com/punteroo/TF2-Item-Plugins/tree/feat/rewrite).

Cuando esto finalice, habra una version actualizada a 2024.
Muchas dependencias han cambiado en este tiempo como TF2Attributes y TFEconData, ademas de que hay cosas para mejorar en los plugins en si.

Por favor pido entiendan que muchas cosas no van a funcionar como se espera debido a estas razones. Gracias!

**Comment by punteroo** [comment]
Por favor, confirmar si los problemas desaparecieron para poder dar cierre a esta Issue.

**Comment by Dylan2004nn** [comment]
ya funciona gracias

**Comment by punteroo** [comment]
Cierro el issue, resuelto con #28
