### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by ghost** [punteroo/TF2-Item-Plugins#3]
not sure if u know this but

**Describe the bug**
Selecting killstreak type after Professional bugs out, causes unknown translation error

**To Reproduce**
1. Type !ks
2. Select weapon
3. Select type three times

**Screenshots**
![image](https://user-images.githubusercontent.com/83210435/116054729-d1986a80-a630-11eb-8d9b-cf098573ef70.png)
probably caused by the `slot + 1` from https://github.com/punteroo/TF2-Item-Plugins/commit/8d2c07f9f9e12e49c94c2abe90d84a851e05a077

**Unrelated error**
![image](https://user-images.githubusercontent.com/83210435/116055140-44094a80-a631-11eb-8f57-129f84c12a2a.png)
happens after disconnect before apply i think, u need to add `IsClientInGame` check

also would u be able to port to [TF2EconData](https://github.com/nosoop/SM-TFEconData) and do an `!item`, `!festivized`, and `!warpaint` plugin and maybe add an admin command to choose for players such as `sm_aussie_force`, `sm_ks_force`, etc?

i would do a pull request for the errors but im lazy

thanks for the plugins!

**Comment by punteroo** [comment]
Hello, thank you for reporting this issue.

For now, I will just fix the problem regarding translations. Never heard of **TF2EconData** before, but by the looks of it I will make a port to that so I can finally ditch **TF2IDB**.

I will mark this for now and update you whenever a new release fixing this is issued. Thank you so much!

**Comment by punteroo** [comment]
Thank you for waiting.

I have issued a hotfix for this with this commit 9f15347a8224c85ab2b741278909fee6b93d7c77
The new ``vip-killstreak`` plugin without this error is up. Thank you for reporting this issue, I will also take into account TF2EconData, whenever I get time to spare I'll port everything over.

I'll leave this issue open, until I do this porting.

**Comment by punteroo** [comment]
Finally posting the final product. This has all been solved thanks to this issue, the port is now complete!

Release v3.0.0 is available here: https://github.com/punteroo/TF2-Item-Plugins/releases/tag/v3.0.0


Thank you for recommending TFEconData to me!
